(async (page) => {
  const results = [];
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const check = (name, pass, evidence) => results.push({ name, pass: Boolean(pass), evidence });
  const state = () => page.evaluate(() => window.colosseum.state());
  const sleep = ms => page.waitForTimeout(ms);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto('about:blank');
  await page.setContent('<input type="file" id="preview-file">');
  await page.locator('#preview-file').setInputFiles('/Users/quentin/workspace/roman-colosseum/dist/colosseum.html');
  const html = await page.locator('#preview-file').evaluate(async el => el.files[0].text());
  await page.setContent(html, { waitUntil: 'domcontentloaded' });
  await page.waitForFunction(() => window.colosseum?.ready);
  await sleep(800);
  const audit = await page.evaluate(() => window.colosseum.auditGeometry());
  console.log('WebGL environment:', await page.evaluate(() => {
    const gl = document.querySelector('#scene').getContext('webgl2');
    const debug = gl.getExtension('WEBGL_debug_renderer_info');
    return { renderer: gl.getParameter(debug?.UNMASKED_RENDERER_WEBGL ?? gl.RENDERER), deviceScaleFactor: devicePixelRatio };
  }));
  check('Geometry has finite positions, normals, UVs, and visible reverse surfaces', audit.nonFinite === 0 && audit.missingNormals === 0 && audit.allDoubleSided, audit);
  await page.screenshot({ path: 'artifacts/exterior.png' });
  const initial = await state();
  await page.locator('#zoom-in').click();
  await sleep(200);
  const zoomed = await state();
  await page.locator('#zoom-out').click();
  await sleep(200);
  check('Zoom buttons move in both directions', zoomed.distance < initial.distance && (await state()).distance > zoomed.distance, { initial: initial.distance, zoomed: zoomed.distance });
  await page.locator('#reset').click();
  const bounds = await page.locator('#scene').boundingBox();
  let totalAngle = 0, previous = (await state()).azimuth;
  for (let i = 0; i < 8; i++) {
    await page.mouse.move(bounds.x + 550, bounds.y + 250);
    await page.mouse.down();
    await page.mouse.move(bounds.x + 280, bounds.y + 250, { steps: 12 });
    await page.mouse.up();
    await sleep(400);
    const angle = (await state()).azimuth;
    let delta = angle - previous;
    while (delta > Math.PI) delta -= Math.PI * 2;
    while (delta < -Math.PI) delta += Math.PI * 2;
    totalAngle += Math.abs(delta); previous = angle;
    if (i === 1 || i === 3 || i === 5) await page.screenshot({ path: `artifacts/orbit-${i}.png` });
  }
  check('Complete exterior orbit via mouse drag', totalAngle >= Math.PI * 2, { degrees: totalAngle * 180 / Math.PI });
  await page.locator('#reset').click();
  await page.locator('#rotate-toggle').click();
  const angleBefore = (await state()).azimuth;
  await sleep(500);
  check('Auto orbit rotates the camera', Math.abs((await state()).azimuth - angleBefore) > .005, (await state()).autoRotate);
  await page.locator('#rotate-toggle').click();
  await page.locator('#labels-toggle').click();
  await sleep(150);
  check('Labels can be hidden', await page.locator('.hotspot:visible').count() === 0);
  await page.locator('#labels-toggle').click();
  await sleep(150);
  await page.locator('[data-hotspot="hypogeum"]').click();
  check('Architectural annotation opens', await page.locator('#feature-card').isVisible());
  await page.locator('#feature-close').click();
  await page.locator('[data-light="golden"]').click();
  await sleep(150);
  await page.screenshot({ path: 'artifacts/golden-hour.png' });
  check('Lighting switches', await page.locator('[data-light="golden"]').getAttribute('aria-pressed') === 'true');
  await page.locator('[data-light="day"]').click();
  for (const view of ['arena', 'seating', 'passages']) {
    await page.locator(`[data-view="${view}"]`).click();
    await sleep(1100);
    const current = await state();
    check(`${view} viewpoint is reachable`, current.view === view && current.position.every(Number.isFinite), current.position);
    await page.screenshot({ path: `artifacts/${view}.png` });
  }
  await page.locator('#walk-toggle').click();
  const passageStart = await state();
  await page.keyboard.down('w'); await sleep(13200); await page.keyboard.up('w');
  const arenaEnd = await state();
  check('Walk continuously from passage to arena', arenaEnd.position[0] < 38 && arenaEnd.position[0] > 13 && arenaEnd.position[1] > 6.5, { from: passageStart.position, to: arenaEnd.position });
  await page.screenshot({ path: 'artifacts/walking-arena.png' });
  await page.keyboard.down('s'); await sleep(13200); await page.keyboard.up('s');
  const passageEnd = await state();
  check('Return through passage without becoming trapped', passageEnd.position[0] > 82, passageEnd.position);
  for (const view of ['arena', 'seating', 'passages', 'exterior']) {
    await page.locator(`[data-view="${view}"]`).click();
    const before = await state();
    await page.keyboard.down('s'); await sleep(550); await page.keyboard.up('s');
    await page.keyboard.press('r');
    const after = await state();
    check(`${view} walking location resets safely`, after.walking && Math.hypot(...after.position.map((n, i) => n - before.position[i])) < .1, after.position);
  }
  await page.keyboard.press('Escape');
  check('Escape always returns to overview', !(await state()).walking && (await state()).view === 'exterior');
  await page.locator('#about-open').click();
  check('Reference notes open with source links', await page.locator('#about-dialog').isVisible() && await page.locator('#about-dialog a').count() === 6);
  await page.keyboard.press('Escape');
  await page.locator('#help-open').click();
  check('Navigation help opens', await page.locator('#help-dialog').isVisible());
  await page.keyboard.press('Escape');
  await page.locator('#fullscreen').click();
  await sleep(150);
  check('Fullscreen enters', await page.evaluate(() => Boolean(document.fullscreenElement)));
  await page.locator('#fullscreen').click();
  await sleep(150);
  check('Fullscreen exits', await page.evaluate(() => !document.fullscreenElement));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('#reset').click(); await sleep(300);
  await page.screenshot({ path: 'artifacts/mobile.png' });
  const mobile = await page.evaluate(() => ({ width: innerWidth, scrollWidth: document.documentElement.scrollWidth, canvas: document.querySelector('#scene').getBoundingClientRect().width }));
  check('Mobile layout fits without horizontal overflow', mobile.scrollWidth <= mobile.width && mobile.canvas > 0, mobile);
  await page.locator('#walk-toggle').click();
  const mobileBefore = await state();
  const moveButton = await page.locator('[data-move="KeyW"]').boundingBox();
  await page.mouse.move(moveButton.x + moveButton.width / 2, moveButton.y + moveButton.height / 2);
  await page.mouse.down();
  await sleep(500);
  await page.mouse.up();
  const mobileAfter = await state();
  check('On-screen walking controls move the camera', mobileAfter.position[0] < mobileBefore.position[0] - .5, mobileAfter.position);
  await page.keyboard.press('Escape');
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.locator('#reset').click();
  check('No browser runtime errors', errors.length === 0, errors);
  return { passed: results.filter(result => result.pass).length, failed: results.filter(result => !result.pass).length, results };
})
