(async (page) => {
  const state = () => page.evaluate(() => window.colosseum.state());
  const sleep = ms => page.waitForTimeout(ms);
  const hold = async (key, ms) => { await page.keyboard.down(key); await sleep(ms); await page.keyboard.up(key); };
  const results = [];
  const check = (name, pass, evidence) => {
    results.push({ name, pass: Boolean(pass), evidence });
    console.log(`${pass ? 'PASS' : 'FAIL'}: ${name}`, pass ? '' : evidence);
  };
  if ((await state()).walking) await page.keyboard.press('Escape');
  await page.locator('[data-view="arena"]').click(); await sleep(1000);
  await page.locator('#walk-toggle').click();
  const bounds = await page.locator('#scene').boundingBox();
  const yaw = Math.atan2(56, 5);
  await hold('a', 940);
  await page.mouse.move(bounds.x + 170, bounds.y + 290);
  await page.mouse.down();
  await page.mouse.move(bounds.x + 170 + (yaw + Math.PI / 2) / .004, bounds.y + 290, { steps: 15 });
  await page.mouse.up();
  await hold('w', 6500);
  let current = await state();
  check('Ascend arena side stair to cavea lookout', current.position[0] > 54 && current.position[1] > 12.6, current.position);
  await page.screenshot({ path: 'artifacts/walking-cavea.png' });
  await hold('s', 6500);
  current = await state();
  check('Descend side stair back to arena platform', current.position[0] < 38 && current.position[1] < 7.5, current.position);
  await page.locator('[data-view="arena"]').click();
  await page.mouse.move(bounds.x + 400, bounds.y + 290);
  await page.mouse.down();
  await page.mouse.move(bounds.x + 400 + (yaw - Math.PI / 2) / .004, bounds.y + 290, { steps: 4 });
  await page.mouse.up();
  await hold('w', 12600);
  current = await state();
  check('Cross boardwalk above hypogeum', current.position[0] < -20 && Math.abs(current.position[2]) < 1.3 && current.position[1] > 6.5, current.position);
  await hold('d', 2000);
  current = await state();
  check('Walkway edge prevents falling into hypogeum', Math.abs(current.position[2]) < 1.85 && current.position[1] > 6.5, current.position);
  await page.keyboard.press('r');
  check('Recover from walkway edge', (await state()).position[0] === 31, (await state()).position);
  await page.keyboard.press('Escape');
  return { passed: results.filter(r => r.pass).length, failed: results.filter(r => !r.pass).length, results };
})
